import { createHash } from "node:crypto";
import { createWriteStream } from "node:fs";
import { mkdir, readFile, rename, stat, writeFile } from "node:fs/promises";
import { extname, join, resolve } from "node:path";
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";
type Product = { productPageUrl: string; productId: string | null; name: string | null; gender: string; images: Array<{ url: string; position: number; title: string | null }> };
type Entry = { url: string; localPath: string; products: Array<{ productPageUrl: string; productId: string | null; name: string | null; gender: string; position: number; title: string | null }> };
const args = process.argv.slice(2); const option = (flag: string, fallback: string) => { const index = args.indexOf(flag); return index >= 0 ? args[index + 1] : fallback; }; const output = resolve(option("--output", "./data")); const imageDir = resolve(option("--images", join(output, "uniqlo-images"))); const delayMs = Number(option("--delay-ms", "250")); const timeoutMs = Number(option("--timeout-ms", "30000")); const retries = Number(option("--retries", "3")); const concurrency = Math.max(1, Number(option("--concurrency", "2"))); const refresh = args.includes("--refresh");
const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms)); const exists = (path: string) => stat(path).then(() => true).catch(() => false); const products: Product[] = (await readFile(join(output, "uniqlo-products.jsonl"), "utf8")).trim().split("\n").filter(Boolean).map(line => JSON.parse(line)); const entries = new Map<string, Entry>();
for (const product of products) for (const image of product.images) { let entry = entries.get(image.url); if (!entry) { const extension = extname(new URL(image.url).pathname) || ".jpg"; entry = { url: image.url, localPath: join(imageDir, `${createHash("sha256").update(image.url).digest("hex").slice(0, 16)}${extension}`), products: [] }; entries.set(image.url, entry); } entry.products.push({ productPageUrl: product.productPageUrl, productId: product.productId, name: product.name, gender: product.gender, position: image.position, title: image.title }); }
const queue = [...entries.values()]; await mkdir(imageDir, { recursive: true }); let succeeded = 0, skipped = 0, failed = 0;
async function download(entry: Entry): Promise<void> { if (!refresh && await exists(entry.localPath)) { skipped++; return; } for (let attempt = 0; attempt <= retries; attempt++) try { if (attempt) await sleep(250 * 2 ** (attempt - 1)); const response = await fetch(entry.url, { signal: AbortSignal.timeout(timeoutMs), headers: { "user-agent": "uniqlo-catalogue-importer/1.0 (prototype research; image download)" } }); if (!response.ok || !response.body) throw new Error(`HTTP ${response.status}`); const temporary = `${entry.localPath}.part`; await pipeline(Readable.fromWeb(response.body as never), createWriteStream(temporary)); await rename(temporary, entry.localPath); succeeded++; return; } catch { if (attempt === retries) failed++; } }
async function worker(): Promise<void> { while (queue.length) { const entry = queue.shift(); if (entry) { await download(entry); if (delayMs) await sleep(delayMs); } } } await Promise.all(Array.from({ length: concurrency }, worker));
await writeFile(join(output, "uniqlo-images-manifest.json"), JSON.stringify({ downloadedAt: new Date().toISOString(), imageDirectory: imageDir, entries: [...entries.values()] }, null, 2) + "\n"); console.log(JSON.stringify({ requested: entries.size, succeeded, skipped, failed, imageDir }, null, 2));
